services:
  - type: web
    name: fomo-backend
    env: python
    plan: free

    buildCommand: cd backend && ./build.sh
    startCommand: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fomodb-production
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: WEB_CONCURRENCY
        value: "4"

      - key: DJANGO_DEBUG
        value: "False"

databases:
  - name: fomodb-production
    plan: free
    databaseName: fomodb
